test_meson_exe_windows (__main__.CommandTests) ... skipped 'NOT IMPLEMENTED'
test_meson_installed (__main__.CommandTests) ... /usr/lib/python3.9/vendor-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
test_meson_uninstalled (__main__.CommandTests) ... ok
test_meson_zipapp (__main__.CommandTests) ... ok
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/_pytest/main.py", line 267, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/_pytest/terminal.py", line 712, in pytest_sessionstart
INTERNALERROR>     lines = self.config.hook.pytest_report_header(
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pytest_randomly/__init__.py", line 189, in pytest_report_header
INTERNALERROR>     _reseed(config)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pytest_randomly/__init__.py", line 168, in _reseed
INTERNALERROR>     eps = entry_points(
INTERNALERROR> TypeError: entry_points() got an unexpected keyword argument 'group'
  [ERROR]    common: 103 has header symbol
  [ERROR]    linuxlike: 3 linker script
  [ERROR]    rust: 5 polyglot static
  [ERROR]    rust: 13 external c dependencies    (static=True method=system)
  [ERROR]    frameworks: 1 boost    (static=false)
  [ERROR]    frameworks: 4 qt    (method=config-tool)
  [ERROR]    frameworks: 4 qt    (method=pkg-config)
  [ERROR]    frameworks: 4 qt    (method=qmake)
  [ERROR]    frameworks: 25 hdf5    (method=config-tool)
  [ERROR]    frameworks: 28 gir link order 2
  [ERROR]    frameworks: 31 curses    (method=config-tool)
  [ERROR]    frameworks: 31 curses    (method=system)
Total passed tests:  537
Total failed tests:  12
Total skipped tests: 118
test cases/common/103 has header symbol/meson.build:16:2: ERROR: Assert failed: FILE structure is defined in stdio.h, not stdlib.h
FAILED: libbob.so 
FAILED: libbob-conf.so 
FAILED: libbob-files.so 
FAILED: libbar.so 
FAILED: sub/libfoo.so 
FAILED: prog 
FAILED: prog 
FAILED: extralibexe 
44/3 qt5test      FAIL               killed by signal 9 SIGKILL
45/3 qt5maninclude FAIL               killed by signal 9 SIGKILL
46/3 qt5subfolder FAIL               killed by signal 9 SIGKILL
test cases/frameworks/4 qt/meson.build:48:4: ERROR: Assert failed: qtmodule.has_tools()
55/3 qt5test      FAIL               killed by signal 9 SIGKILL
56/3 qt5maninclude FAIL               killed by signal 9 SIGKILL
57/3 qt5subfolder FAIL               killed by signal 9 SIGKILL
FAILED: exef.p/main.f90.o 
FAILED: libsample.so 
FAILED: basic 
FAILED: basic 
