============================= test session starts ==============================
collected 634 items
==================================== ERRORS ====================================
stdout = 'Processing /tmp/pytest-of-andreas/pytest-10/magic0\nBuilding wheels for collected packages: com.magic.this-is-fun\n  ...py clean for com.magic.this-is-fun\nFailed to build com.magic.this-is-fun\nERROR: Failed to build one or more wheels\n'
stdout     = 'Processing /tmp/pytest-of-andreas/pytest-10/magic0\nBuilding wheels for collected packages: com.magic.this-is-fun\n  ...py clean for com.magic.this-is-fun\nFailed to build com.magic.this-is-fun\nERROR: Failed to build one or more wheels\n'
E             Building wheels for collected packages: com.magic.this-is-fun
=================================== FAILURES ===================================
ERROR: invocation failed (exit code 1)
ERROR: invocation failed (exit code 1)
ERROR: invocation failed (exit code 1)
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
ERROR: ... command /usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 py37 (exited with code 1)
ERROR: ... command /usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 py37 (exited with code 1)
E       ================================== log start ===================================
E       =================================== log end ====================================
ERROR: ... command /usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 py37 (exited with code 1)
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
ERROR: invocation failed (exit code 1)
E         ================================== log start ===================================
E         =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pyte...on3.7/vendor-packages/tox/__main__.py", line 1, in <module>
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pyte...on3.7/vendor-packages/tox/__main__.py", line 1, in <module>
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pyte...on3.7/vendor-packages/tox/__main__.py", line 1, in <module>
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
E       ================================== log start ===================================
E       =================================== log end ====================================
=============================== warnings summary ===============================
===Flaky Test Report===
test_parallel_interrupt failed (2 runs remaining out of 3).
test_parallel_interrupt failed (1 runs remaining out of 3).
test_parallel_interrupt failed; it passed 0 out of the required 1 times.
test_parallel_live failed (2 runs remaining out of 3).
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_live0/pkg123/.tox/.package/log/.package-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR: InvocationError for command /usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 .package (exited with code 1)
ERROR: FAIL could not package project - v = InvocationError('/usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 .package', 1)
test_parallel_live failed (1 runs remaining out of 3).
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_live1/pkg123/.tox/.package/log/.package-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR: InvocationError for command /usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 .package (exited with code 1)
ERROR: FAIL could not package project - v = InvocationError('/usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 .package', 1)
test_parallel_live failed; it passed 0 out of the required 1 times.
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_live2/pkg123/.tox/.package/log/.package-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR: InvocationError for command /usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 .package (exited with code 1)
ERROR: FAIL could not package project - v = InvocationError('/usr/bin/python3.7 -m virtualenv --no-download --python /usr/bin/python3.7 .package', 1)
test_parallel_show_output failed (2 runs remaining out of 3).
================================== log start ===================================
=================================== log end ====================================
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_show_output0/pkg123/.tox/e1/log/e1-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_show_output0/pkg123/.tox/e2/log/e2-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR:   e1: parallel child exit code 1
ERROR:   e2: parallel child exit code 1
ERROR:   e3: parallel child exit code 1
test_parallel_show_output failed (1 runs remaining out of 3).
================================== log start ===================================
=================================== log end ====================================
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_show_output1/pkg123/.tox/e1/log/e1-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_show_output1/pkg123/.tox/e3/log/e3-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR:   e1: parallel child exit code 1
ERROR:   e2: parallel child exit code 1
ERROR:   e3: parallel child exit code 1
test_parallel_show_output failed; it passed 0 out of the required 1 times.
================================== log start ===================================
=================================== log end ====================================
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_show_output2/pkg123/.tox/e1/log/e1-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_show_output2/pkg123/.tox/e3/log/e3-0.log
================================== log start ===================================
=================================== log end ====================================
ERROR:   e1: parallel child exit code 1
ERROR:   e2: parallel child exit code 1
ERROR:   e3: parallel child exit code 1
===End Flaky Test Report===
=========================== short test summary info ============================
SKIPPED [1] integration/test_jython_env_create.py:5: needs jython and dev cut of virtualenv
SKIPPED [1] unit/test_z_cmdline.py:776: Platform doesnt support alwayscopy
SKIPPED [1] unit/interpreters/windows/test_pep514.py:10: non posix test
SKIPPED [1] unit/interpreters/windows/test_pep514.py:17: non posix test
SKIPPED [1] unit/interpreters/windows/test_windows.py:4: non posix test
ERROR unit/test_result.py::test_invocation_error[posix-None]
ERROR unit/test_result.py::test_invocation_error[posix-0]
ERROR unit/test_result.py::test_invocation_error[posix-5]
ERROR unit/test_result.py::test_invocation_error[posix-143]
ERROR unit/test_result.py::test_invocation_error[posix-1234]
ERROR unit/test_result.py::test_invocation_error[posix--15]
ERROR unit/test_result.py::test_invocation_error[nt-None]
ERROR unit/test_result.py::test_invocation_error[nt-0]
ERROR unit/test_result.py::test_invocation_error[nt-5]
ERROR unit/test_result.py::test_invocation_error[nt-143]
ERROR unit/test_result.py::test_invocation_error[nt-1234]
ERROR unit/test_result.py::test_invocation_error[nt--15]
ERROR unit/test_venv.py::test_create_KeyboardInterrupt[_pcall]
ERROR unit/test_venv.py::test_create_KeyboardInterrupt[update]
ERROR unit/test_venv.py::test_run_install_command_handles_KeyboardInterrupt
ERROR unit/test_z_cmdline.py::test_exit_code[0]
ERROR unit/test_z_cmdline.py::test_exit_code[6]
ERROR unit/interpreters/test_interpreters.py::test_tox_get_python_executable
ERROR unit/interpreters/test_interpreters.py::test_find_alias_on_path
ERROR unit/interpreters/test_interpreters.py::TestInterpreters::test_get_executable
ERROR unit/interpreters/test_interpreters.py::TestInterpreters::test_get_executable_no_exist
ERROR unit/interpreters/test_interpreters.py::TestInterpreters::test_get_sitepackagesdir_error
ERROR unit/session/test_provision.py::test_provision_non_canonical_dep - Asse...
ERROR unit/util/test_spinner.py::test_spinner_stdout_not_unicode
ERROR unit/util/test_spinner.py::test_spinner_report_not_unicode
FAILED integration/test_package_int.py::test_package_setuptools - AssertionEr...
FAILED integration/test_package_int.py::test_package_flit - AssertionError: 2
FAILED integration/test_package_int.py::test_package_poetry - AssertionError: 2
FAILED integration/test_parallel_inception.py::test_parallel_inception - Asse...
FAILED integration/test_parallel_interrupt.py::test_parallel_interrupt - Asse...
FAILED integration/test_provision_int.py::test_provision_missing - AssertionE...
FAILED integration/test_provision_int.py::test_provision_from_pyvenv - Assert...
FAILED integration/test_provision_int.py::test_provision_interrupt_child[Signals.SIGINT]
FAILED integration/test_provision_int.py::test_provision_interrupt_child[Signals.SIGTERM]
FAILED unit/test_z_cmdline.py::test_recreate - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_unknown_dep - AssertionError: assert False
FAILED unit/test_z_cmdline.py::test_venv_special_chars_issue252 - AssertionEr...
FAILED unit/test_z_cmdline.py::test_toxuone_env - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_different_config_cwd - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_result_json - AssertionError: missing test
FAILED unit/test_z_cmdline.py::test_developz - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_usedevelop - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_usedevelop_mixed - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_test_usedevelop[.-False] - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_test_usedevelop[.-True] - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_test_usedevelop[src-False] - AssertionErr...
FAILED unit/test_z_cmdline.py::test_test_usedevelop[src-True] - AssertionErro...
FAILED unit/test_z_cmdline.py::test_warning_emitted - AssertionError: assert ...
FAILED unit/test_z_cmdline.py::test_alwayscopy_default - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_empty_activity_ignored - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_empty_activity_shown_verbose - AssertionE...
FAILED unit/test_z_cmdline.py::test_test_piphelp - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_notest - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_devenv[True] - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_devenv[False] - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_PYC - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_env_VIRTUALENV_PYTHON - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_setup_prints_non_ascii - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_envsitepackagesdir - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_verbosity[] - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_verbosity[-v] - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_verbosity[-vv] - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_envtmpdir - AssertionError: 1
FAILED unit/test_z_cmdline.py::test_tox_console_script - FileNotFoundError: [...
FAILED unit/test_z_cmdline.py::test_tox_quickstart_script - FileNotFoundError...
FAILED unit/config/test_config.py::test_config_current_py - AssertionError: 1
FAILED unit/package/test_package.py::test_build_backend_without_submodule - A...
FAILED unit/package/test_package_view.py::test_separate_sdist - AssertionErro...
FAILED unit/package/builder/test_package_builder_isolated.py::test_isolated_build_backend_missing_hook
FAILED unit/session/test_parallel.py::test_parallel - AssertionError: 2
FAILED unit/session/test_parallel.py::test_parallel_live - AssertionError: 2
FAILED unit/session/test_parallel.py::test_parallel_error_report[True] - Asse...
FAILED unit/session/test_parallel.py::test_parallel_error_report[False] - AssertionError: [K⠋ [0] ERROR: invocation failed (exit code 1), logfile: /tmp/pytest-of-andreas/pytest-10/test_parallel_error_report_Fal0/pkg123/.tox/a/log/a-0.log
FAILED unit/session/test_parallel.py::test_parallel_show_output - AssertionEr...
FAILED unit/session/test_parallel.py::test_parallel_no_spinner_on - Assertion...
FAILED unit/session/test_parallel.py::test_parallel_no_spinner_off - Assertio...
FAILED unit/session/test_parallel.py::test_parallel_no_spinner_not_set - Asse...
FAILED unit/session/test_parallel.py::test_parallel_result_json - AssertionEr...
FAILED unit/session/test_parallel.py::test_parallel_result_json_concurrent - ...
FAILED unit/session/test_provision.py::test_provision_cli_args_ignore - Asser...
FAILED unit/session/test_provision.py::test_provision_does_not_fail_with_no_provision_no_reason[None]
FAILED unit/session/test_provision.py::test_provision_does_not_fail_with_no_provision_no_reason[missing.json]
FAILED unit/session/test_provision.py::test_provision_does_not_fail_with_satisfied_requires[None]
FAILED unit/session/test_provision.py::test_provision_does_not_fail_with_satisfied_requires[missing.json]
FAILED unit/session/test_provision.py::test_provision_requirement_with_environment_marker
FAILED unit/session/test_session.py::test_skip_sdist - AssertionError: 1
FAILED unit/session/test_session.py::test_tox_env_var_flags_inserted_non_isolated
FAILED unit/session/test_session.py::test_tox_env_var_flags_inserted_isolated
FAILED unit/session/test_show_config.py::test_showconfig_with_force_dep_version
FAILED unit/session/test_show_config.py::test_showconfig[all] - AssertionErro...
FAILED unit/session/test_show_config.py::test_showconfig[default_only] - Asse...
FAILED unit/session/test_show_config.py::test_showconfig_interpolation - Asse...
FAILED unit/session/test_show_config.py::test_config_specific_ini - Assertion...
FAILED unit/session/test_show_config.py::test_override_workdir - assert 'over...
====== 69 failed, 535 passed, 5 skipped, 3 warnings, 25 errors =======
