--- urllib3-2.0.4/test/with_dummyserver/test_https.py.orig
+++ urllib3-2.0.4/test/with_dummyserver/test_https.py
@@ -541,6 +541,7 @@
                 https_pool.request("GET", "/", retries=0)
             assert isinstance(cm.value.reason, SSLError)
 
+    @pytest.mark.skip(reason="sometimes fails: https://github.com/urllib3/urllib3/issues/3111")
     def test_verify_none_and_good_fingerprint(self) -> None:
         with HTTPSConnectionPool(
             "127.0.0.1",
--- urllib3-2.0.4/test/with_dummyserver/test_socketlevel.py.orig
+++ urllib3-2.0.4/test/with_dummyserver/test_socketlevel.py
@@ -1766,6 +1766,7 @@
             assert expected_request_headers == filter_non_x_headers(self.parsed_headers)
 
     @resolvesLocalhostFQDN()
+    @pytest.mark.skip(reason="fails with 'Connection refused'")
     def test_request_host_header_ignores_fqdn_dot(self) -> None:
         self.start_parsing_handler()
 
